version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command:
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run:
          name: Check formatting
          command:
            go fmt ./...
      - run:
          name: Check lint
          command:
            golangci-lint run ./...
      - run:
          name: Check test
          command:
            go test -v ./...
